### ISSUE TITLE
CI: add vars for NX cloud

### ISSUE THREAD

**Issue by benjamincharity** [GetTerminus/terminus-oss#514]
```yml
env:
  NX_BRANCH: ${{ github.event.number }}
  NX_RUN_GROUP: ${{ github.run_id }}
```
